name: DeepSpeech-Keras
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - blosc=1.14.4
  - bzip2=1.0.6
  - ca-certificates=2018.03.07=0
  - certifi=2018.11.29
  - dill==0.2.8.2
  - h5py=2.9.0
  - hdf5=1.10.4
  - intel-openmp=2019.1=144
  - lzo=2.10
  - mkl=2019.1=144
  - mkl_fft=1.0.6
  - mkl_random=1.0.2
  - numexpr=2.6.8
  - numpy=1.15.4
  - numpy-base=1.15.4
  - openssl=1.1.1a
  - pip=18.1
  - pytables=3.4.4
  - python=3.6.7
  - setuptools=40.6.2
  - six=1.12.0
  - snappy=1.1.7
  - sqlite=3.25.3
  - tk=8.6.8
  - wheel=0.32.3
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - absl-py==0.7.0
    - astor==0.7.1
    - atomicwrites==1.3.0
    - attrs==19.1.0
    - cycler==0.10.0
    - dataclasses==0.6
    - gast==0.2.2
    - grpcio==1.19.0
    - joblib==0.13.2
    - keras==2.2.4
    - keras-applications==1.0.7
    - keras-preprocessing==1.0.9
    - kiwisolver==1.0.1
    - markdown==3.0.1
    - matplotlib==3.0.3
    - mock==2.0.0
    - more-itertools==6.0.0
    - munch==2.3.2
    - pandas==0.24.1
    - pbr==5.1.3
    - pluggy==0.9.0
    - protobuf==3.6.1
    - py==1.7.0
    - pyparsing==2.3.1
    - pyspellchecker==0.4.0
    - pytest==4.3.0
    - python-dateutil==2.8.0
    - python-speech-features==0.6
    - pytz==2018.7
    - pyyaml==4.2b4
    - scikit-learn==0.20.3
    - scipy==1.2.1
    - seaborn==0.9.0
    - sklearn==0.0
    - tables==3.4.4
    - tensorboard==1.13.1
    - tensorflow==1.13.1
    - tensorflow-estimator==1.13.0
    - termcolor==1.1.0
    - tqdm==4.31.1
    - werkzeug==0.14.1
    - libstdcxx-ng=8.2.0
    - libgcc-ng=8.2.0
    - readline=7.0
    - libffi=3.2.1
    - libgfortran-ng=7.3.0
    - libedit=3.1.20170329
    - ncurses=6.1
