name: DeepSpeech-Keras
channels:
  - conda-forge
  - defaults
dependencies:
  - absl-py=0.6.1
  - blas=1.0=mkl
  - blosc=1.15.1
  - bzip2=1.0.6
  - dill=0.2.8.2
  - lzo=2.10
  - numexpr=2.6.9
  - pytables=3.4.4
  - setuptools=40.6.3
  - termcolor=1.1.0
  - wheel=0.32.3
  - _tflow_select=2.1.0=gpu
  - astor=0.7.1
  - c-ares=1.15.0
  - ca-certificates=2018.03.07=0
  - certifi=2018.11.29
  - gast=0.2.0
  - grpcio=1.16.1
  - h5py=2.9.0
  - hdf5=1.10.4
  - intel-openmp=2019.1=144
  - keras=2.2.4=0
  - keras-applications=1.0.6
  - keras-base=2.2.4
  - keras-preprocessing=1.0.5
  - libffi=3.2.1
  - libprotobuf=3.6.1
  - markdown=3.0.1
  - mkl=2019.1=144
  - mkl_fft=1.0.6
  - mkl_random=1.0.2
  - numpy=1.15.4
  - numpy-base=1.15.4
  - openssl=1.1.1a
  - pandas=0.23.4
  - pip=18.1
  - protobuf=3.6.1
  - python=3.6.8
  - python-dateutil=2.7.5
  - pytz=2018.7
  - pyyaml=3.13
  - scipy=1.1.0
  - six=1.12.0
  - sqlite=3.26.0
  - tensorboard=1.12.2
  - tensorflow-base=1.12.0
  - tensorflow-gpu=1.12.0
  - tk=8.6.8
  - werkzeug=0.14.1
  - xz=5.2.4
  - yaml=0.1.7
  - zlib=1.2.11
  - pip:
    - libgcc-ng=8.2.0
    - atomicwrites==1.3.0
    - attrs==19.1.0
    - cycler==0.10.0
    - joblib==0.13.2
    - kiwisolver==1.0.1
    - matplotlib==3.0.3
    - mock==2.0.0
    - more-itertools==6.0.0
    - pbr==5.1.3
    - pluggy==0.9.0
    - py==1.8.0
    - pyparsing==2.3.1
    - pytest==4.3.0
    - python_speech_features==0.6
    - seaborn==0.9.0
    - tables==3.4.4
    - tensorflow-estimator==1.13.0
    - tqdm==4.31.1
    - readline=7.0
    - cudatoolkit=9.2=0
    - cudnn=7.2.1=cuda9.2_0
    - cupti=9.2.148
    - ncurses=6.1
    - libstdcxx-ng=8.2.0
    - tensorflow=1.12.0=gpu
    - libedit=3.1.20170329
    - libgfortran-ng=7.3.0
